export const theme = {
  colors: {
    background: "#FFFFFF",
    border: "#EBEBEB",
    card: "#FFFFFF",
    foreground: "#1A1A1A",
    mutedForeground: "#717171",
    offBlack: "#222222",
    primary: "#5F33E1",
    primaryBg: "#EBE5FD",
    primaryLight: "#5F33E1",
    secondary: "#8E8E93",
    greyBg: "#F7F7F7",
    inputBg: "#F7F7F7",
    categoryOrange: "#FFE6D4",
    categoryPink: "#FFE4F2",
    categoryPurple: "#EEEDF9",
    categoryYellow: "#FFF6D4",
    colorError: "#FF3B30",
    colorErrorBg: "#FFEDEB",
    colorInfo: "#007AFF",
    colorInfoBg: "#E5F1FF",
    colorSuccess: "#34C759",
    colorSuccessBg: "#E8F9ED",
    colorWarning: "#FF9500",
    colorWarningBg: "#FFF3E0",
    progressBlue: "#0087FF",
    progressRed: "#FF7D53",
  },
  typography: {
    fontPrimary: "SF Pro Display",
    fontSecondary: "SF Pro Text",
    sizeXs: 11,
    sizeSm: 13,
    sizeMd: 15,
    sizeLg: 17,
    sizeXl: 20,
    size2xl: 24,
    size3xl: 28,
    sizeTitle: 34,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    x2l: 48,
  },
  radius: {
    sm: 8,
    m: 12,
    lg: 16,
    xl: 24,
    pill: 100,
  },
} as const;

export type Theme = typeof theme;

export const cssVars = {
  "--background": theme.colors.background,
  "--border": theme.colors.border,
  "--card": theme.colors.card,
  "--category-orange": theme.colors.categoryOrange,
  "--category-pink": theme.colors.categoryPink,
  "--category-purple": theme.colors.categoryPurple,
  "--category-yellow": theme.colors.categoryYellow,
  "--color-error": theme.colors.colorError,
  "--color-error-bg": theme.colors.colorErrorBg,
  "--color-info": theme.colors.colorInfo,
  "--color-info-bg": theme.colors.colorInfoBg,
  "--color-success": theme.colors.colorSuccess,
  "--color-success-bg": theme.colors.colorSuccessBg,
  "--color-warning": theme.colors.colorWarning,
  "--color-warning-bg": theme.colors.colorWarningBg,
  "--font-primary": theme.typography.fontPrimary,
  "--font-secondary": theme.typography.fontSecondary,
  "--font-size-xs": theme.typography.sizeXs,
  "--font-size-sm": theme.typography.sizeSm,
  "--font-size-md": theme.typography.sizeMd,
  "--font-size-lg": theme.typography.sizeLg,
  "--font-size-xl": theme.typography.sizeXl,
  "--font-size-2xl": theme.typography.size2xl,
  "--font-size-3xl": theme.typography.size3xl,
  "--font-size-title": theme.typography.sizeTitle,
  "--foreground": theme.colors.foreground,
  "--grey-bg": theme.colors.greyBg,
  "--input-bg": theme.colors.inputBg,
  "--muted-foreground": theme.colors.mutedForeground,
  "--off-black": theme.colors.offBlack,
  "--primary": theme.colors.primary,
  "--primary-bg": theme.colors.primaryBg,
  "--primary-light": theme.colors.primaryLight,
  "--progress-blue": theme.colors.progressBlue,
  "--progress-red": theme.colors.progressRed,
  "--radius-sm": theme.radius.sm,
  "--radius-m": theme.radius.m,
  "--radius-lg": theme.radius.lg,
  "--radius-xl": theme.radius.xl,
  "--radius-pill": theme.radius.pill,
  "--secondary": theme.colors.secondary,
  "--spacing-xs": theme.spacing.xs,
  "--spacing-sm": theme.spacing.sm,
  "--spacing-md": theme.spacing.md,
  "--spacing-lg": theme.spacing.lg,
  "--spacing-xl": theme.spacing.xl,
  "--spacing-2xl": theme.spacing.x2l,
} as const;
